CREATE DATABASE IF NOT EXISTS library;
USE library;
SET NAMES 'utf8';
-- 创建图书表 
DROP TABLE IF EXISTS books;
CREATE TABLE books(
id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
bookname VARCHAR(50) NOT NULL,
author_id INT(8) UNSIGNED NOT NULL,
press_id INT(8) UNSIGNED NOT NULL,
pubTime INT UNSIGNED NOT NULL,
quantity INT(2) UNSIGNED NOT NULL,
quantity_left INT(2) UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 创建作者表
DROP TABLE IF EXISTS author;
CREATE TABLE author(
id INT(8) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
email VARCHAR(30) NOT NULL,
phone CHAR(15) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 创建出版社表
DROP TABLE IF EXISTS press;
CREATE TABLE press(
id INT(8) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
email CHAR(30) NOT NULL,
phone CHAR(20) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 创建学生表
DROP TABLE IF EXISTS student;
CREATE TABLE student(
id INT(8) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
stu_index CHAR(10) UNSIGNED NOT NULL,
name  VARCHAR(20) NOT NULL,
age INT(3) UNSIGNED NOT NULL,
academy VARCHAR(50) NOT NULL,
sex enum('男','女','保密') NOT NULL DEFAULT '保密'
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 创建借阅历史表
DROP TABLE IF EXISTS BARinfo;
CREATE TABLE BARinfo(
id INT(8) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
stu_index INT(8) NOT NULL,
book_index INT(8) NOT NULL,
borrowTime CHAR(20)   NOT NULL,
returnTime CHAR(20)  
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 创建管理员表
DROP TABLE IF EXISTS admin;
CREATE TABLE admin(
id INT(4) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
password VARCHAR(32) NOT NULL,
email VARCHAR(40) NOT NULL,
phone CHAR(15) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 创建用户表
DROP TABLE IF EXISTS users;
CREATE TABLE users(
id INT(4) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
password VARCHAR(32) NOT NULL,
email VARCHAR(30) NOT NULL,
phone CHAR(15) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


/*2016/5/7/更新*/
ALTER TABLE books ADD COLUMN owner CHAR(20) NOT NULL;
ALTER TABLE books ADD COLUMN reader CHAR(20) NOT NULL;
ALTER TABLE books ADD COLUMN out_time INT(4) NOT NULL DEFAULT 0;


/*2016/5/8/更新*/

-- 网站访问量和注册数统计表
DROP TABLE IF EXISTS statistics;
CREATE TABLE statistics(
id INT(3) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
visited INT(6) UNSIGNED NOT NULL DEFAULT 0,
registers INT(6) UNSIGNED NOT NULL DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 用户操作日志
DROP TABLE IF EXISTS log;
CREATE TABLE log(
id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
who VARCHAR(20) NOT NULL,
whattime CHAR(20) NOT NULL,
what VARCHAR(20) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT statistics(visited,registers) VALUES('0','0');
ALTER TABLE log ADD COLUMN ip CHAR(40) NOT NULL;
ALTER TABLE log MODIFY COLUMN what VARCHAR(40) NOT NULL;






